services:
    backend:
        container_name: backend
        build: ./backend
        command: npm run dev
        volumes:
            - ./backend:/backend
        ports:
            - "3001:3001"
    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile-frontend
        ports:
            - '5173:5173'
        volumes:
            - ./frontend:/app
            - /app/node_modules
